# Generated by Django 5.1.2 on 2024-10-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdoit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='made',
        ),
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
