# Generated by Django 5.1.2 on 2024-10-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed_before',
            new_name='complete_before',
        ),
    ]
