# Generated by Django 5.1.2 on 2024-10-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_completed_before_task_complete_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated_ad',
            new_name='update_ad',
        ),
    ]
