# Generated by Django 5.1.2 on 2024-10-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_created_at_task_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='update_ad',
            new_name='updated_at',
        ),
    ]
